""" This module contains the definition of the MOM-So systems used in the """

# SINGLE_OVERHEAD_DECONTI = [
#     {
#         'line_id': 0,
#         'conductor_name': 'p',
#         'line_type': 'active',
#         'line_return': None,
#         'center_point': (0, 10),
#         'radius': [0, 0.01],
#         'conductivity': 6.496E7,
#         'subconductors': None,
#         'insulation': None,
#         'relative_permeability': 1,
#         'relative_permittivity': 1,
#         'relative_permittivity_out': 1,
#         'fourier_order': 0,
#     }
# ]

# SINGLE_OVERHEAD_XUE = [
#     {
#         'line_id': 0,
#         'conductor_name': 'p',
#         'line_type': 'active',
#         'line_return': None,
#         'center_point': (0, 10),
#         'radius': [0, 0.01],
#         'conductivity': 1/1.68E-8,
#         'subconductors': None,
#         'insulation': None,
#         'relative_permeability': 1,
#         'relative_permittivity': 1,
#         'relative_permittivity_out': 1,
#         'fourier_order': 0,
#     }
# ]

# TL_138kV_OVERHEAD = [
#     {
#         'line_id': 0,
#         'conductor_name': 'p',
#         'line_type': 'active',
#         'line_return': 3,
#         'center_point': (0, 10),
#         'radius': [0, 0.01],
#         'conductivity': 6.496E7,
#         'subconductors': None,
#         'insulation': None,
#         'relative_permeability': 1,
#         'relative_permittivity': 1,
#         'relative_permittivity_out': 1,
#         'fourier_order': 0,
#     },
#     {
#         'line_id': 1,
#         'conductor_name': 'q',
#         'line_type': 'active',
#         'line_return': 3,
#         'center_point': (0, 10),
#         'radius': [0, 0.01],
#         'conductivity': 6.496E7,
#         'subconductors': None,
#         'insulation': None,
#         'relative_permeability': 1,
#         'relative_permittivity': 1,
#         'relative_permittivity_out': 1,
#         'fourier_order': 0,
#     },
#     {
#         'line_id': 2,
#         'conductor_name': 'r',
#         'line_type': 'active',
#         'line_return': 3,
#         'center_point': (0, 10),
#         'radius': [0, 0.01],
#         'conductivity': 6.496E7,
#         'subconductors': None,
#         'insulation': None,
#         'relative_permeability': 1,
#         'relative_permittivity': 1,
#         'relative_permittivity_out': 1,
#         'fourier_order': 0,
#     },
#     {
#         'line_id': 3,
#         'conductor_name': 'guard-wire',
#         'line_type': 'return',
#         'line_return': None,
#         'center_point': (0, 0),
#         'radius': [0, 0.01],
#         'conductivity': 6.496E7,
#         'subconductors': None,
#         'insulation': None,
#         'relative_permeability': 1,
#         'relative_permittivity': 1,
#         'relative_permittivity_out': 1,
#         'soil_relative_permeability': 1,
#         'soil_relative_permittivity': 5,
#         'soil_conductivity': 1/200,
#         'fourier_order': 0,
#     },
#     {
#         'line_id': 3,
#         'conductor_name': 'soil',
#         'line_type': 'return',
#         'line_return': None,
#         'center_point': None,
#         'radius': None,
#         'conductivity': 6.496E7,
#         'subconductors': None,
#         'insulation': None,
#         'relative_permeability': 1,
#         'relative_permittivity': 1,
#         'relative_permittivity_out': 1,
#         'fourier_order': 0,
#     }
# ]

# COAXIAL_CABLE = [
#     {
#         'line_id': 1,
#         'conductor_name': 'core',
#         'line_type': 'active',
#         'line_return': 0,
#         'center_point': (0, 0),
#         'radius': [0, 0.022],
#         'conductivity': 5.8E7,
#         'subconductors': None,
#         'insulation': None,
#         'conductor_layers': 0,
#         'relative_permeability': 1,
#         'relative_permittivity': 1,
#         'relative_permittivity_out': 1,
#         'fourier_order': 0,
#     },
#     {
#         'line_id': 0,
#         'conductor_name': 'sheath',
#         'line_type': 'return',
#         'line_return': None,
#         'center_point': (0, 0),
#         'radius': [0.0395, 0.044],
#         'conductivity': 5.8E7,
#         'subconductors': None,
#         'insulation': None,
#         'conductor_layers': 1,
#         'relative_permeability': 1,
#         'relative_permittivity': 1,
#         'relative_permittivity_out': 1,
#         'fourier_order': 0,
#     }
# ]

BIFILAR_BARE_WIRE_S21 = {
    'type': 'bare_wires',
    'ref': 'Clements (1974)',
    0: {
        'line_id': 0,
        'conductor_name': 'q',
        'line_type': 'return',
        'line_return': None,
        'center_point': (0.0, 0.0),
        'radius': [0, 0.010],
        'conductivity': 1/1.68E-8,
        'subconductors': None,
        'sheath': None,
        'relative_permeability': 1.0,
        'relative_permittivity': 1.0,
        'relative_permittivity_out': 1.0,
        'potential_to_infinity': -1.0,
        'fourier_order': 12,
    },
    1: {
        'line_id': 1,
        'conductor_name': 'p',
        'line_type': 'active',
        'line_return': 0,
        'center_point': (0.021, 0.0),
        'radius': [0, 0.010],
        'conductivity': 1/1.68E-8,
        'subconductors': None,
        'sheath': None,
        'relative_permeability': 1.0,
        'relative_permittivity': 1.0,
        'relative_permittivity_out': 1.0,
        'potential_to_infinity': 1.0,
        'fourier_order': 12,
    },
}

BIFILAR_COATED_WIRE_S40 = {
    'type': 'coated_wires',
    'ref': 'Clements (1974)',
    0: {
        'line_id': 0,
        'conductor_name': 'q',
        'line_type': 'return',
        'line_return': None,
        'center_point': (0.0, 0.0),
        'radius': [0, 0.010],
        'conductivity': 1/1.68E-8,
        'subconductors': None,
        'sheath': {'name': 'coated',
                    'center_point': (0.0, 0.0),
                    'thickness': 0.010,
                    'fourier_order': 2,
                    'relative_permittivity': 3.0},
        'relative_permeability': 1.0,
        'relative_permittivity': 1.0,
        'relative_permittivity_out': 1.0,
        'potential_to_infinity': -1.0,
        'fourier_order': 2,
    },
    1: {
        'line_id': 1,
        'conductor_name': 'p',
        'line_type': 'active',
        'line_return': 0,
        'center_point': (0.040, 0.0),
        'radius': [0, 0.010],
        'conductivity': 1/1.68E-8,
        'subconductors': None,
        'sheath': {'name': 'coated',
                    'center_point': (0.040, 0.0),
                    'thickness': 0.010,
                    'fourier_order': 2,
                    'relative_permittivity': 3.0},
        'relative_permeability': 1.0,
        'relative_permittivity': 1.0,
        'relative_permittivity_out': 1.0,
        'potential_to_infinity': 1.0,
        'fourier_order': 2,
    },    
}

