""" This module contains the definition of the MOM-So systems used in the """
LINNET = { 'type': 'ACSR',
    'radius': {'value': [6.74E-3/2, 18.29E-3/2], 'unit': 'm'},
    'resistance_20': {'value': 0.1695, 'unit': 'ohm/km'},
    'resistance_65': {'value': 0.2002, 'unit': 'ohm/km'},
    'conductivity': None,
}

STEEL_3_8 = { 'type': 'Steel',
    'radius': {'value': [0, 9.52E-3/2], 'unit': 'm'},
    'resistance_20': {'value': 3.81, 'unit': 'ohm/km'},
    'resistance_65': {'value': 4.5815, 'unit': 'ohm/km'},
    'conductivity': None,
}

CMTM = 2.54E-5 # 1 mil in meters

PAUL_RIBBON_CABLE = {
    'name': 'PAUL_RIBBON_CABLE',
    'type': 'coated_wires',
    'note': 'Original Paul (2008) problem',
    'idx_ref_conductor': 0,
    0: {
        'line_id': 0,
        'conductor_name': 'p',
        'line_type': 'return',
        'line_return': None,
        'center_point': (0.0, 0.0),
        'radius': [0, 7.5*CMTM],
        'conductivity': 1/1.68E-8,
        'subconductors': None,
        'insulation': {'name': 'primary_insulation',
                    'center_point': (0.0, 0.0),
                    'thickness': 10.0*CMTM,
                    'fourier_order': 4,
                    'relative_permittivity': 3.5},
        'relative_permeability': 1.0,
        'relative_permittivity': 1.0,
        'relative_permittivity_out': 1.0,
        'potential_to_infinity': -1.0,
        'fourier_order': 4,
    },
    1: {
        'line_id': 1,
        'conductor_name': 'q',
        'line_type': 'active',
        'line_return': 0,
        'center_point': (50*CMTM, 0.0),
        'radius': [0, 7.5*CMTM],
        'conductivity': 1/1.68E-8,
        'subconductors': None,
        'insulation': {'name': 'primary_insulation',
                    'center_point': (50*CMTM, 0.0),
                    'thickness': 10.0*CMTM,
                    'fourier_order': 4,
                    'relative_permittivity': 3.5},
        'relative_permeability': 1.0,
        'relative_permittivity': 1.0,
        'relative_permittivity_out': 1.0,
        'potential_to_infinity': -1.0,
        'fourier_order': 4,
    },
    2: {
        'line_id': 2,
        'conductor_name': 'r',
        'line_type': 'active',
        'line_return': 0,
        'center_point': (100*CMTM, 0.0),
        'radius': [0, 7.5*CMTM],
        'conductivity': 1/1.68E-8,
        'subconductors': None,
        'insulation': {'name': 'primary_insulation',
                    'center_point': (100*CMTM, 0.0),
                    'thickness': 10.0*CMTM,
                    'fourier_order': 4,
                    'relative_permittivity': 3.5},
        'relative_permeability': 1.0,
        'relative_permittivity': 1.0,
        'relative_permittivity_out': 1.0,
        'potential_to_infinity': -1.0,
        'fourier_order': 4,
    },    
}

BIFILAR_COATED_WIRE_S4000 = {
    'name': 'BIFILAR_COATED_WIRE_S4000',
    'type': 'coated_wires',
    'note': 'Original Clements (1974) problem',
    'idx_ref_conductor': 0,
    0: {
        'line_id': 0,
        'conductor_name': 'q',
        'line_type': 'return',
        'line_return': None,
        'center_point': (0.0, 0.0),
        'radius': [0, 1.0E0],
        'conductivity': 1/1.68E-8,
        'subconductors': None,
        'insulation': {'name': 'primary_insulation',
                    'center_point': (0.0, 0.0),
                    'thickness': 1.0E0,
                    'fourier_order': 1,
                    'relative_permittivity': 3.0},
        'relative_permeability': 1.0,
        'relative_permittivity': 1.0,
        'relative_permittivity_out': 1.0,
        'potential_to_infinity': -1.0,
        'fourier_order': 10,
    },
    1: {
        'line_id': 1,
        'conductor_name': 'p',
        'line_type': 'active',
        'line_return': 0,
        'center_point': (4.0E0, 0.0),
        'radius': [0, 1.0E0],
        'conductivity': 1/1.68E-8,
        'subconductors': None,
        'insulation': {'name': 'primary_insulation',
                    'center_point': (4.0E0, 0.0),
                    'thickness': 1.0E0,
                    'fourier_order': 1,
                    'relative_permittivity': 3.0},
        'relative_permeability': 1.0,
        'relative_permittivity': 1.0,
        'relative_permittivity_out': 1.0,
        'potential_to_infinity': 1.0,
        'fourier_order': 10,
    },    
}

BIFILAR_COATED_WIRE_S40_K0 = {
    'name': 'BIFILAR_COATED_WIRE_S40_K0',
    'type': 'coated_wires',
    'note': 'Modified Clements (1974) problem with conductor radii rw=10mm',
    'idx_ref_conductor': 0,
    0: {
        'line_id': 0,
        'conductor_name': 'q',
        'line_type': 'return',
        'line_return': None,
        'center_point': (0.0, 0.0),
        'radius': [0, 0.010],
        'conductivity': 1/1.68E-8,
        'subconductors': None,
        'insulation': {'name': 'primary_insulation',
                    'center_point': (0.0, 0.0),
                    'thickness': 0.010,
                    'fourier_order': 0,
                    'relative_permittivity': 3.0},
        'relative_permeability': 1.0,
        'relative_permittivity': 1.0,
        'relative_permittivity_out': 1.0,
        'potential_to_infinity': -1.0,
        'fourier_order': 0,
    },
    1: {
        'line_id': 1,
        'conductor_name': 'p',
        'line_type': 'active',
        'line_return': 0,
        'center_point': (0.040, 0.0),
        'radius': [0, 0.010],
        'conductivity': 1/1.68E-8,
        'subconductors': None,
        'insulation': {'name': 'primary_insulation',
                    'center_point': (0.040, 0.0),
                    'thickness': 0.010,
                    'fourier_order': 0,
                    'relative_permittivity': 3.0},
        'relative_permeability': 1.0,
        'relative_permittivity': 1.0,
        'relative_permittivity_out': 1.0,
        'potential_to_infinity': 1.0,
        'fourier_order': 0,
    },    
}

BIFILAR_COATED_WIRE_S40_K10 = {
    'name': 'BIFILAR_COATED_WIRE_S40_K10',
    'type': 'coated_wires',
    'note': 'Modified Clements (1974) problem with conductor radii rw=10mm',
    'idx_ref_conductor': 0,
    0: {
        'line_id': 0,
        'conductor_name': 'q',
        'line_type': 'return',
        'line_return': None,
        'center_point': (-0.020, 0.0),
        'radius': [0, 0.010],
        'conductivity': 1/1.68E-8,
        'subconductors': None,
        'insulation': {'name': 'primary_insulation',
                    'center_point': (-0.020, 0.0),
                    'thickness': 0.010,
                    'fourier_order': 10,
                    'relative_permittivity': 3.0},
        'relative_permeability': 1.0,
        'relative_permittivity': 1.0,
        'relative_permittivity_out': 1.0,
        'potential_to_infinity': -1.0,
        'fourier_order': 10,
    },
    1: {
        'line_id': 1,
        'conductor_name': 'p',
        'line_type': 'active',
        'line_return': 0,
        'center_point': (0.020, 0.0),
        'radius': [0, 0.010],
        'conductivity': 1/1.68E-8,
        'subconductors': None,
        'insulation': {'name': 'primary_insulation',
                    'center_point': (0.020, 0.0),
                    'thickness': 0.010,
                    'fourier_order': 10,
                    'relative_permittivity': 3.0},
        'relative_permeability': 1.0,
        'relative_permittivity': 1.0,
        'relative_permittivity_out': 1.0,
        'potential_to_infinity': 1.0,
        'fourier_order': 10,
    },    
}

BIFILAR_BARE_WIRE_S21_K10 = {
    'name': 'BIFILAR_BARE_WIRE_S21_K10',
    'type': 'bare_wires',
    'note': 'Modified Clements (1974) problem with conductor radii rw=10mm',
    'idx_ref_conductor': 0,
    0: {
        'line_id': 0,
        'conductor_name': 'q',
        'line_type': 'return',
        'line_return': None,
        'center_point': (0.0, 0.0),
        'radius': [0, 0.010],
        'conductivity': 1/1.68E-8,
        'subconductors': None,
        'insulation': None,
        'relative_permeability': 1.0,
        'relative_permittivity': 1.0,
        'relative_permittivity_out': 1.0,
        'potential_to_infinity': -1.0,
        'fourier_order': 10,
    },
    1: {
        'line_id': 1,
        'conductor_name': 'p',
        'line_type': 'active',
        'line_return': 0,
        'center_point': (0.021, 0.0),
        'radius': [0, 0.010],
        'conductivity': 1/1.68E-8,
        'subconductors': None,
        'insulation': None,
        'relative_permeability': 1.0,
        'relative_permittivity': 1.0,
        'relative_permittivity_out': 1.0,
        'potential_to_infinity': 1.0,
        'fourier_order': 10,
    },
}

COAXIAL_CABLE = {
    'name': 'COAXIAL_CABLE',
    'type': 'coaxial',
    'note': 'Patel (2014) Coaxial cable model',
    'idx_ref_conductor': 0,
    0: {
        'line_id': 0,
        'conductor_name': 'sheath',
        'line_type': 'return',
        'line_return': None,
        'center_point': (0.0, 0.0),
        'radius': [0.0395, 0.0440],
        'conductivity': 5.8E7,
        'subconductors': None,
        'insulation': None,
        'conductor_layers': None,
        'relative_permeability': 1.0,
        'relative_permittivity': 1.0,
        'relative_permittivity_out': 1.0,
        'potential_to_infinity': -1.0,
        'fourier_order': 0,
    },
    1: {
        'line_id': 1,
        'conductor_name': 'core',
        'line_type': 'active',
        'line_return': 0,
        'center_point': (0.0, 0.0),  # Positive numbers denotes cable depth
        'radius': [0, 0.0220],
        'conductivity': 5.8E7,
        'subconductors': None,
        'insulation': {'name': 'primary_insulation',
                        'center_point': (0.0, 0.0),
                        'thickness': 0.0175,
                        'fourier_order': 0,
                        'relative_permittivity': 1.0},
        'conductor_layers': None,
        'relative_permeability': 1.0,
        'relative_permittivity': 1.0,
        'relative_permittivity_out': 1.0,
        'potential_to_infinity': 1.0,
        'fourier_order': 0,
    },
}

SINGLE_WIRE_R10_LIMA = {
    'name': 'SINGLE_WIRE_R10_LIMA',
    'type': 'overhead',
    'note': 'Lima e Tomasevich (2015) model',
    'idx_ref_conductor': 0,
    0: {
        'line_id': 0,
        'conductor_name': 'soil',
        'line_type': 'return',
        'line_return': None,
        'center_point': None,
        'radius': None,
        'conductivity': 5e-3,
        'subconductors': None,
        'insulation': None,
        'conductor_layers': None,
        'relative_permeability': 1.0,
        'relative_permittivity': 5.0,
        'external_conductance': 18.641e-12,
        'relative_permittivity_out': 1.0,
        'potential_to_infinity': +1.0,
        'fourier_order': 0,
    },
    1: {
        'line_id': 1,
        'conductor_name': 'p',
        'line_type': 'active',
        'line_return': 0,
        'center_point': (0.0, 10.0),
        'radius': [0, 0.010],
        'conductivity': 6.496E7,
        'subconductors': None,
        'insulation': None,
        'conductor_layers': 1,
        'relative_permeability': 1.0,
        'relative_permittivity': 1.0,
        'external_conductance': 18.641e-12,
        'relative_permittivity_out': 1.0,
        'potential_to_infinity': -1.0,
        'fourier_order': 0,
    },
}

SINGLE_WIRE_R05 = {
    'name': 'SINGLE_WIRE_R05',
    'type': 'overhead',
    'note': 'De Conti (2021) model',
    'idx_ref_conductor': 0,
    0: {
        'line_id': 0,
        'conductor_name': 'soil',
        'line_type': 'return',
        'line_return': None,
        'center_point': None,
        'radius': None,
        'conductivity': 0.005,
        'subconductors': None,
        'insulation': None,
        'conductor_layers': None,
        'relative_permeability': 1.0,
        'relative_permittivity': 5.0,
        'external_conductance': 0.0,
        'relative_permittivity_out': 1.0,
        'potential_to_infinity': +1.0,
        'fourier_order': 0,
    },
    1: {
        'line_id': 1,
        'conductor_name': 'p',
        'line_type': 'active',
        'line_return': 0,
        'center_point': (0.0, 10.0),
        'radius': [0, 0.0005],
        'conductivity': 5.8E7,
        'subconductors': None,
        'insulation': None,
        'conductor_layers': 1,
        'relative_permeability': 1.0,
        'relative_permittivity': 1.0,
        'external_conductance': 0.0,
        'relative_permittivity_out': 1.0,
        'potential_to_infinity': -1.0,
        'fourier_order': 0,
    },
}

SINGLE_WIRE_R10_XUE = {
    'name': 'SINGLE_WIRE_R10_XUE',
    'type': 'overhead',
    'note': 'Xue (2018) model',
    'idx_ref_conductor': 0,
    0: {
        'line_id': 0,
        'conductor_name': 'soil',
        'line_type': 'return',
        'line_return': None,
        'center_point': None,
        'radius': None,
        'conductivity': 0.010, # rho_g = 100 Ohm.m
        'subconductors': None,
        'insulation': None,
        'conductor_layers': None,
        'relative_permeability': 1.0,
        'relative_permittivity': 1.0,
        'external_conductance': 0.0,
        'relative_permittivity_out': 1.0,
        'potential_to_infinity': +1.0,
        'fourier_order': 0,
    },
    1: {
        'line_id': 1,
        'conductor_name': 'p',
        'line_type': 'active',
        'line_return': 0,
        'center_point': (0.0, 10.0),
        'radius': [0, 0.010],
        'conductivity': 1/1.68E-8,
        'subconductors': None,
        'insulation': None,
        'conductor_layers': None,
        'relative_permeability': 1.0,
        'relative_permittivity': 1.0,
        'external_conductance': 0.0,
        'relative_permittivity_out': 1.0,
        'potential_to_infinity': -1.0,
        'fourier_order': 0,
    },
}

SINGLE_WIRE_R468 = {
    'name': 'SINGLE_WIRE_R468',
    'type': 'overhead',
    'note': 'De Conti (2021) model',
    'idx_ref_conductor': 0,
    0: {
        'line_id': 0,
        'conductor_name': 'soil',
        'line_type': 'return',
        'line_return': None,
        'center_point': None,
        'radius': None,
        'conductivity': 0.001,
        'subconductors': None,
        'insulation': None,
        'conductor_layers': None,
        'relative_permeability': 1.0,
        'relative_permittivity': 1.0,
        'external_conductance': 0.0,
        'relative_permittivity_out': 1.0,
        'potential_to_infinity': +1.0,
        'fourier_order': 0,
    },
    1: {
        'line_id': 1,
        'conductor_name': 'p',
        'line_type': 'active',
        'line_return': 0,
        'center_point': (0.0, 8.40),
        'radius': [0, 0.00468],
        'conductivity': 3.8E7, # Aluminum Conductivity
        'subconductors': None,
        'insulation': None,
        'conductor_layers': 1,
        'relative_permeability': 1.0,
        'relative_permittivity': 1.0,
        'external_conductance': 0.0,
        'relative_permittivity_out': 1.0,
        'potential_to_infinity': -1.0,
        'fourier_order': 0,
    },
}