""" This module contains the definition of the systems. """

BIFILAR_S100 = [
    {
        'line_id': 0,
        'conductor_name': 'p',
        'subconductor_id': 1,
        'line_type': 'active',
        'line_return': 1,
        'center_point': (0, 0),
        'radius': [0, 0.01],
        'thickness': None,
        'conductivity': 5.8E7,
        'subconductors': None,
        'insulation': None,
        'relative_permeability': 1,
        'relative_permittivity': 1,
        'relative_permittivity_out': 1,
        'surface_points': 1,
    },
    {
        'line_id': 1,
        'conductor_name': 'q',
        'subconductor_id': 2,
        'line_type': 'return',
        'line_return': 'null',
        'center_point': (0.100, 0),
        'radius': [0, 0.01],
        'thickness': None,
        'conductivity': 5.8E7,
        'subconductors': None,
        'insulation': None,
        'relative_permeability': 1,
        'relative_permittivity': 1,
        'relative_permittivity_out': 1,
        'surface_points': 1,
    }
]

BIFILAR_S25 = [
    {
        'line_id': 0,
        'conductor_name': 'p',
        'subconductor_id': 1,
        'line_type': 'active',
        'line_return': 1,
        'center_point': (0, 0),
        'radius': [0, 0.01],
        'thickness': None,
        'conductivity': 5.8E7,
        'subconductors': None,
        'insulation': None,
        'relative_permeability': 1,
        'relative_permittivity': 1,
        'relative_permittivity_out': 1,
        'surface_points': 3,
    },
    {
        'line_id': 1,
        'conductor_name': 'q',
        'subconductor_id': 2,
        'line_type': 'return',
        'line_return': 'null',
        'center_point': (0.025, 0),
        'radius': [0, 0.01],
        'thickness': None,
        'conductivity': 5.8E7,
        'subconductors': None,
        'insulation': None,
        'relative_permeability': 1,
        'relative_permittivity': 1,
        'relative_permittivity_out': 1,
        'surface_points': 3,
    }
]

SCC = [
    {
        'line_id': 0,
        'conductor_name': 'sheath',
        'line_type': 'return',
        'line_return': None,
        'center_point': (0, 0),
        'radius': [0.0395, 0.044],
        'conductivity': 5.8E7,
        'conductor_layers': 1,
        'relative_permeability': 1,
        'relative_permittivity': 1,
        'relative_permittivity_out': 1,
        'surface_points': 0,
    },
    {
        'line_id': 1,
        'conductor_name': 'core',
        'line_type': 'active',
        'line_return': 0,
        'center_point': (0, 0),
        'radius': [0, 0.022],
        'conductivity': 5.8E7,
        'conductor_layers': 0,
        'relative_permeability': 1,
        'relative_permittivity': 1,
        'relative_permittivity_out': 1,
        'surface_points': 0,
    }
]

SCC_ASYMMETRIC = [
    {
        'line_id': 0,
        'conductor_name': 'core',
        'subconductor_id': 1,
        'line_type': 'active',
        'line_return': 1,
        'center_point': (0, 0.010),
        'radius': [0, 0.022],
        'thickness': None,
        'conductivity': 5.8E7,
        'conductor_layers': 0,
        'relative_permeability': 1,
        'relative_permittivity': 1,
        'relative_permittivity_out': 1,
        'surface_points': 0,
    },
    {
        'line_id': 1,
        'conductor_name': 'sheath',
        'subconductor_id': 2,
        'line_type': 'return',
        'line_return': None,
        'center_point': (0, 0),
        'radius': [0.0395, 0.044],
        'thickness': None,
        'conductivity': 5.8E7,
        'conductor_layers': 1,
        'relative_permeability': 1,
        'relative_permittivity': 1,
        'relative_permittivity_out': 1,
        'surface_points': 0,
    }
]

TREFOIL = [
    {
        'line_id': 0,
        'conductor_name': 'core',
        'subconductor_id': 1,
        'line_type': 'active',
        'line_return': 1,
        'center_point': (0, 0),
        'radius': [0, 0.010],
        'thickness': None,
        'conductivity': 5.8E7,
        'subconductors': {'layers': 'no'},
        'insulation': {'name': 'primary',
                       'thickness': 0.004,
                       'relative_permittivity': 2.3},
        'relative_permeability': 1,
        'relative_permittivity': 1,
        'relative_permittivity_out': 1,
        'surface_points': 0,
    },
    {
        'line_id': 1,
        'conductor_name': 'screen',
        'subconductor_id': 2,
        'line_type': 'return',
        'line_return': 'null',
        'center_point': (0, 0),
        'radius': None,
        'thickness': None,
        'conductivity': 5.8E7,
        'subconductors': {'layers': 1,
                          'wires_per_layer': 50,
                          'wire_radius': 0.0005},
        'insulation': {'name': 'secondary',
                       'thickness': 2.76799135492708E-3,
                       'relative_permittivity': 2.3},
        'relative_permeability': 1,
        'relative_permittivity': 1,
        'relative_permittivity_out': 1,
        'surface_points': 0,
    },
    {
        'line_id': 2,
        'conductor_name': 'armor',
        'subconductor_id': 3,
        'line_type': 'return',
        'line_return': 'null',
        'center_point': (0, 0),
        'radius': [0, 0.08826/2],
        'thickness': None,
        'conductivity': 1E7,
        'subconductors': {'layers': 2,
                          'wires_per_layer': 70,
                          'wire_radius': 0.003/2},
        'insulation': {'name': 'jacket',
                       'thickness': 0.002,
                       'relative_permittivity': 2.3},
        'relative_permeability': 100,
        'relative_permittivity': 1,
        'relative_permittivity_out': 1,
        'surface_points': 0,
    }
]

COAXIAL_SHELLS = [
    {
        'line_id': 0,
        'conductor_name': 'p',
        'subconductor_id': 1,
        'line_type': 'active',
        'line_return': 1,
        'center_point': (0, 0),
        'radius': [0.016, 0.020],
        'thickness': None,
        'conductivity': 5.8E7,
        'conductor_layers': 1,
        'relative_permeability': 1,
        'relative_permittivity': 1,
        'relative_permittivity_out': 1,
        'surface_points': 0,
    },
    {
        'line_id': 1,
        'conductor_name': 'q',
        'subconductor_id': 2,
        'line_type': 'return',
        'line_return': 'null',
        'center_point': (0.045, 0),
        'radius': [0.016, 0.020],
        'thickness': None,
        'conductivity': 5.8E7,
        'conductor_layers': 1,
        'relative_permeability': 1,
        'relative_permittivity': 1,
        'relative_permittivity_out': 1,
        'surface_points': 0,
    },
    {
        'line_id': 1,
        'conductor_name': 'r',
        'subconductor_id': 3,
        'line_type': 'return',
        'line_return': 'null',
        'center_point': (0.090, 0),
        'radius': [0.016, 0.020],
        'thickness': None,
        'conductivity': 5.8E7,
        'conductor_layers': 1,
        'relative_permeability': 1,
        'relative_permittivity': 1,
        'relative_permittivity_out': 1,
        'surface_points': 0,
    }
]

SCC_UNDERGROUND = [
    {
        'line_id': 0,
        'name': 'core',
        'line_type': 'active',
        'line_return': 2,
        'center_point': (0, -1),
        'radius': [0, 0.1],
        'thickness': None,
        'conductivity': 5.8E7,
        'subconductors': {'layers': 'no'},
        'relative_permittivity': 1,
        'relative_permeability': 1,
        'surface_points': 0,
    },
    {
        'line_id': 1,
        'name': 'primary_insulation',
        'line_type': 'hole',
        'line_return': 2,
        'center_point': (0, -1),
        'radius': [0, 0.5],
        'thickness': None,
        'conductivity': None,
        'subconductors': {'layers': 'no'},
        'relative_permittivity': 2.3,
        'relative_permeability': 1,
        'surface_points': 1,
    },
    {
        'line_id': 2,
        'name': 'ground',
        'line_type': 'return',
        'line_return': None,
        'center_point': None,
        'radius': None,
        'thickness': None,
        'conductivity': 0.01,
        'subconductors': {'layers': 'no'},
        'relative_permittivity': 1,
        'relative_permeability': 1,
        'surface_points': None,
    }
]

DCC_UNDERGROUND = [
    {
        'line_id': 0,
        'name': 'core',
        'line_type': 'active',
        'line_return': 1,
        'center_point': (-0.2, -1),
        'radius': [0, 0.1],
        'thickness': None,
        'conductivity': 5.8E7,
        'subconductors': {'layers': 'no'},
        'relative_permittivity': 1,
        'relative_permeability': 1,
        'surface_points': 0,
    },
    {
        'line_id': 1,
        'name': 'core',
        'line_type': 'active',
        'line_return': 1,
        'center_point': (0.2, -1),
        'radius': [0, 0.1],
        'thickness': None,
        'conductivity': 5.8E7,
        'subconductors': {'layers': 'no'},
        'relative_permittivity': 1,
        'relative_permeability': 1,
        'surface_points': 0,
    },
    {
        'line_id': 2,
        'name': 'primary_insulation',
        'line_type': 'hole',
        'line_return': None,
        'center_point': (0, -1),
        'radius': [0, 0.5],
        'thickness': None,
        'conductivity': None,
        'subconductors': {'layers': 'no'},
        'relative_permittivity': 2.3,
        'relative_permeability': 1,
        'surface_points': 0,
    }
]

SCC_UNDERGROUND_3PH = [
    {
        'line_id': 0,
        'conductor_name': 'core',
        'subconductor_id': 1,
        'line_type': 'active',
        'line_return': 1,
        'center_point': (0, -1),
        'radius': [0, 0.01],
        'thickness': None,
        'conductivity': 5.8E7,
        'subconductors': {'layers': 'no'},
        'insulation': {'name': 'primary',
                       'center_point': (0, -1),
                       'thickness': 0.020,
                       'relative_permittivity': 2.3},
        'relative_permeability': 1,
        'relative_permittivity': 1,
        'relative_permittivity_out': 1,
        'surface_points': 0,
    },
    {
        'line_id': 1,
        'conductor_name': 'core',
        'subconductor_id': 2,
        'line_type': 'active',
        'line_return': 1,
        'center_point': (0.5, -1),
        'radius': [0, 0.01],
        'thickness': None,
        'conductivity': 5.8E7,
        'subconductors': {'layers': 'no'},
        'insulation': {'name': 'primary',
                       'center_point': (0.5, -1),
                       'thickness': 0.020,
                       'relative_permittivity': 2.3},
        'relative_permeability': 1,
        'relative_permittivity': 1,
        'relative_permittivity_out': 1,
        'surface_points': 0,
    },
    {
        'line_id': 2,
        'conductor_name': 'core',
        'subconductor_id': 3,
        'line_type': 'active',
        'line_return': 1,
        'center_point': (-0.5, -1),
        'radius': [0, 0.01],
        'thickness': None,
        'conductivity': 5.8E7,
        'subconductors': {'layers': 'no'},
        'insulation': {'name': 'primary',
                       'center_point': (-0.5, -1),
                       'thickness': 0.020,
                       'relative_permittivity': 2.3},
        'relative_permeability': 1,
        'relative_permittivity': 1,
        'relative_permittivity_out': 1,
        'surface_points': 0,
    }
]

ENCLOSURE_GIB = [
    {
        'line_id': 0,
        'conductor_name': 'metallic-tank',
        'line_type': 'return',
        'line_return': None,
        'center_point': (0, 0),
        'radius': [0.0265, 0.0303],
        'conductivity': 1/1.3E-7,
        'relative_permittivity': 1,
        'relative_permeability': 78,
        'relative_permittivity_out': 1,
        'surface_points': 0,
    },
    {
        'line_id': 1,
        'conductor_name': 'a-phase',
        'line_type': 'active',
        'line_return': 0,
        'center_point': (-0.0132, 0),
        'radius': [0.005, 0.006],
        'conductivity': 1/2.8E-8,
        'relative_permittivity': 1,
        'relative_permeability': 1,
        'relative_permittivity_out': 1,
        'surface_points': 0,
    },
    {
        'line_id': 2,
        'conductor_name': 'c-phase',
        'line_type': 'active',
        'line_return': 0,
        'center_point': (0.0132, 0),
        'radius': [0.005, 0.006],
        'conductivity': 1/2.8E-8,
        'relative_permittivity': 1,
        'relative_permeability': 1,
        'relative_permittivity_out': 1,
        'surface_points': 0,
    },
    {
        'line_id': 3,
        'conductor_name': 'c-phase',
        'line_type': 'active',
        'line_return': 0,
        'center_point': (0, -0.0132),
        'radius': [0.005, 0.006],
        'conductivity': 1/2.8E-8,
        'relative_permittivity': 1,
        'relative_permeability': 1,
        'relative_permittivity_out': 1,
        'surface_points': 0,
    }
]

TRANSMISSION_LINE = [
    {'file_name': 'mom_so_two_wire_line_s100',
        'type': 'bifilar_wires',
        'data': BIFILAR_S100,
     },
    {'file_name': 'mom_so_two_wire_line_s25',
        'type': 'bifilar_wires',
        'data': BIFILAR_S25,
     },
    {'file_name': 'mom_so_single_core_cable',
        'type': 'scc',
        'data': SCC,
     },
    {'file_name': 'mom_so_single_core_cable',
        'type': 'scc_asymmetric',
        'data': SCC_ASYMMETRIC,
     },
    {'file_name': 'mom_so_single_core_cable_sw',
        'type': 'scc_screen_wires',
        'data': SCC,
     },
    {'file_name': 'mom_so_trefoil_power_cable',
        'type': 'trefoil',
        'data': TREFOIL,
     },
    {'file_name': 'mom_so_two_coaxial_shells',
        'type': 'coaxial_shells',
        'data': COAXIAL_SHELLS,
     },
    {'file_name': 'mom_so_core_insulation',
        'type': 'cable_hole',
        'data': SCC_UNDERGROUND,
     },
    {'file_name': 'mom_so_tanaka_gib',
        'type': 'enclosure_gib',
        'data': ENCLOSURE_GIB,
    }
]
